#! /bin/bash

# data is expected to be in a dir ~/helix/Atlas/Nebula/data/$ID
id="09"

src="/Users/jordancampbell/helix/Atlas/Nebula/data/$id"
dst="/Users/jordancampbell/helix/Atlas/Nebula/Unity/Nebula/Assets/Resources"

# this will rewrite the data from <filename.json to data.json
python Unity/main.py write draw

echo '[Nebula] Cleaning resources dir '
rm $dst/NebulaTextures/*.jpg
rm $dst/NebulaTextures/*.meta
rm $dst/data.json

echo '[Nebula] Loading assets... '
cp $src/data.json $dst/
cp $src/*.jpg $dst/NebulaTextures/

echo '[Nebula] Complete.'

















# END
